name: Run Python Script Daily at 11 AM

on:
  workflow_dispatch:
  schedule:
    # Runs at 11:00 AM IST (5:30 AM UTC)
    - cron: '30 1 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          tesseract --version

      - name: Install Python dependencies
        working-directory: webscrapper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        working-directory: webscrapper/eauctionsindiabot
        run: python main.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
